### PR TITLE
Add docs for Redis connector v2.1.0 and v2.2.0

### PR DESCRIPTION
**Pull request by sajinieKavindya**
Related Prs: wso2-extensions/esb-connector-redis#26, wso2-extensions/esb-connector-redis#29

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

**Comment by samgnaniah** [comment]
Is the same example doc still valid for all versions?

**Comment by samgnaniah** [comment]
This is relevant for API-M 4.0.0 docs as well right? Can we send a PR there for the same fix?

**Comment by sajinieKavindya** [comment]
> This is relevant for API-M 4.0.0 docs as well right? Can we send a PR there for the same fix?

https://github.com/wso2/docs-apim/pull/4293

**Comment by sajinieKavindya** [comment]
> Is the same example doc still valid for all versions?

yes.

**Review by Vathsan — APPROVED** [review]

**Review by samgnaniah — APPROVED** [review]

**Pull request merged**
